name: Tkvtv New Web Site
description: Blogging about stuffs
meta_description: "Tkvtv New Web Site, Blogging about stuffs"

markdown:     kramdown
highlighter:  pygments
logo:         false
paginate:     15
baseurl:      https://takagotch.github.io/page34
domain_name: 'https://takagotch.github.io/page34'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://takagotch.github.io/page34'
author:         'Takashi Yoshioka'

